---
- name: Enable TRIM
  become: true
  shell: yes | trimforce enable
  when: macos_ssd.trim

- name: Enable Sudden Motion Sensor
  become: true
  shell: pmset -a sms 1
  when: macos_ssd.sms

- name: Set no access time
  become: true
  when: macos_ssd.noatime
  blockinfile:
      path: "{{ macos_ssd.noatime_plist }}"
      block: |
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
        <key>Label</key>
        <string>com.noatime</string>
        <key>ProgramArguments</key>
        <array>
        <string>mount</string>
        <string>-uwo</string>
        <string>noatime</string>
        <string>/</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        </dict>
        </plist>